# Flujo de CI para automatización web Java
# Autor: ChristianJaimes
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Ejecutar pruebas
        run: ./gradlew clean test -Dheadless=true
